version: '3.6'
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env.development.local
  #   depends_on:
  #     - mongodb
  #     - redis

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    command: /bin/sh -c "redis-cli --requirepass $$REDIS_PASS"
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

volumes:
  mongo_data:
  redis_data:
